name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install choosenim
      run: |
        curl -O https://nim-lang.org/choosenim/init.sh
        sh init.sh -y
        echo 'export PATH=~/.nimble/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Select Nim version
      run: |
        choosenim 2.0.2

    - name: Check atlas installation
      run: |
        if ! command -v atlas &> /dev/null
        then
            echo "atlas could not be found"
            exit 1
        fi
